# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://tick-lab.github.io'
baseurl: ''
title: 'Tick Borne Research Laboratory'
description: 'University of North Texas HSC'
permalink: pretty

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: People
  url: /people/
- title: Publications
  url: /pubs/
- title: Tick Testing Services
  url: https://www.unthsc.edu/graduate-school-of-biomedical-sciences/molecular-and-medical-genetics/tick-borne-disease-research-laboratory/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    feature_image: img/IMG_3077_1300x400.png
